#!/usr/bin/make -f

all:
	make -C wifi.cgi
	make -C iostatus.cgi
	make -C ioswitch.cgi
	make -C ioconfig.cgi

clean:
	make -C wifi.cgi clean
	make -C iostatus.cgi clean
	make -C ioswitch.cgi clean
	make -C ioconfig.cgi clean

install:
	make -C wifi.cgi install
	make -C iostatus.cgi install
	make -C ioswitch.cgi install
	make -C ioconfig.cgi install

uninstall:
	make -C wifi.cgi uninstall
	make -C iostatus.cgi uninstall
	make -C ioswitch.cgi uninstall
	make -C ioconfig.cgi uninstall
