#!/usr/bin/make -f

all:
	make -C dompi_gpio
#	make -C dompi_alarma

clean:
	make -C dompi_gpio clean
#	make -C dompi_alarma clean

install:
	make -C dompi_gpio install
#	make -C dompi_alarma install

uninstall:
	make -C dompi_gpio uninstall
#	make -C dompi_alarma uninstall
